name: build
on:
  push:
    branches:
      - main
  schedule:
    # Run this script every 1 hrs
    #  */m hr day month day_of_week
    - cron:  '0 */1 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: run
        run: |
          yarn
          yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          single-commit: true
          git-config-email: <>
          branch: gh-pages 
          folder: dist
