name: build
on:
  push:
    branches:
      - main
  schedule:
    # Run this script every 4 hrs
    - cron:  '9 */4 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: run
        run: |
          yarn
          yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          single-commit: true
          git-config-email: <>
          branch: gh-pages 
          folder: dist
